const data = {
  smartPhones: {
    models: [
      {
        id: "s1",
        brand: "Samsung",
        model: "Galaxy S21",
        price: 999,
        color: [
          "Phantom Gray",
          "Phantom White",
          "Phantom Violet",
          "Phantom Pink",
        ],
        storage: "128GB",
        camera: "64 Megapixels",
        screen: "6.2 inches",
        img: "https://picsum.photos/200/300?model=galaxy-s21",
        description:
          "Experience the future with the Samsung Galaxy S21. This flagship smartphone boasts a stunning 6.2-inch screen, a powerful 64MP camera, and 128GB of storage. Its sleek design and Phantom color options make it a standout choice.",
      },
      {
        id: "s2",
        brand: "Samsung",
        model: "Galaxy Note 20",
        price: 1099,
        color: ["Mystic Bronze", "Mystic Black", "Mystic Green"],
        storage: "256GB",
        camera: "108 Megapixels",
        screen: "6.7 inches",
        img: "https://picsum.photos/200/300?model=galaxy-note-20",
        description:
          "Elevate your mobile experience with the Samsung Galaxy Note 20. With a massive 6.7-inch screen, a cutting-edge 108MP camera, and 256GB of storage, it's a powerhouse for productivity and creativity. Choose from Mystic Bronze, Black, or Green.",
      },
      {
        id: "a1",
        brand: "Apple",
        model: "iPhone 12",
        price: 1099,
        color: ["Graphite", "Silver", "Gold", "Pacific Blue"],
        storage: "256GB",
        camera: "12 Megapixels",
        screen: "6.1 inches",
        img: "https://picsum.photos/200/300?model=iphone-12",
        description:
          "Introducing the iPhone 12, Apple's latest masterpiece. With a 6.1-inch Super Retina XDR display, a powerful 12MP camera system, and 256GB of storage, it sets a new standard for smartphones. Choose from stunning colors like Graphite, Silver, Gold, and Pacific Blue.",
      },
      {
        id: "a2",
        brand: "Apple",
        model: "iPhone SE",
        price: 399,
        color: ["Black", "White", "Product(RED)"],
        storage: "64GB",
        camera: "12 Megapixels",
        screen: "4.7 inches",
        img: "https://picsum.photos/200/300?model=iphone-se",
        description:
          "Compact yet powerful, the iPhone SE delivers incredible performance. With a 4.7-inch Retina HD display, a 12MP camera, and 64GB of storage, it's perfect for those who prefer a smaller form factor. Choose from classic colors like Black, White, and Product(RED).",
      },
      {
        id: "h1",
        brand: "Huawei",
        model: "Mate 40",
        price: 1099,
        color: ["Black", "Silver", "Green"],
        storage: "256GB",
        camera: "50 Megapixels",
        screen: "6.5 inches",
        img: "https://picsum.photos/200/300?model=huawei-mate-40",
        description:
          "Experience innovation with the Huawei Mate 40. This smartphone features a 6.5-inch display, a powerful 50MP camera, and 256GB of storage. Choose from stylish colors like Black, Silver, and Green.",
      },
      {
        id: "xia1",
        brand: "Xiaomi",
        model: "Mi 11",
        price: 899,
        color: ["Blue", "White", "Black"],
        storage: "128GB",
        camera: "108 Megapixels",
        screen: "6.81 inches",
        img: "https://picsum.photos/200/300?model=xiaomi-mi-11",
        description:
          "Discover the Xiaomi Mi 11, a smartphone that pushes boundaries. With a 108MP camera, a 6.81-inch display, and 128GB of storage, it's a perfect blend of style and performance. Available in Blue, White, and Black.",
      },
      {
        id: "s3",
        brand: "Samsung",
        model: "Galaxy S21 Ultra",
        price: 1299,
        color: ["Phantom Black", "Phantom Silver", "Phantom Navy"],
        storage: "256GB",
        camera: "108 Megapixels",
        screen: "6.8 inches",
        img: "https://picsum.photos/200/300?model=galaxy-s21-ultra",
        description:
          "Experience the pinnacle of mobile technology with the Samsung Galaxy S21 Ultra. Featuring a massive 108MP camera, a 6.8-inch display, and 256GB of storage, it's designed for those who demand the best.",
      },
      {
        id: "a3",
        brand: "Apple",
        model: "iPhone 13 Pro",
        price: 1199,
        color: ["Sierra Blue", "Graphite", "Gold", "Silver"],
        storage: "512GB",
        camera: "12 Megapixels",
        screen: "6.1 inches",
        img: "https://picsum.photos/200/300?model=iphone-13-pro",
        description:
          "Introducing the iPhone 13 Pro, Apple's latest innovation. With a 6.1-inch ProMotion XDR display, a powerful 12MP camera system, and 512GB of storage, it sets new standards for performance and style.",
      },
      {
        id: "h2",
        brand: "Huawei",
        model: "P40 Pro",
        price: 1099,
        color: ["Deep Sea Blue", "Ice White", "Silver Frost"],
        storage: "256GB",
        camera: "50 Megapixels",
        screen: "6.58 inches",
        img: "https://picsum.photos/200/300?model=huawei-p40-pro",
        description:
          "Capture the world in stunning detail with the Huawei P40 Pro. Featuring a 50MP camera, a 6.58-inch display, and 256GB of storage, it's a smartphone designed for photography enthusiasts.",
      },
      {
        id: "xia2",
        brand: "Xiaomi",
        model: "Redmi Note 10",
        price: 299,
        color: ["Aqua Green", "Frost White", "Shadow Black"],
        storage: "128GB",
        camera: "48 Megapixels",
        screen: "6.43 inches",
        img: "https://picsum.photos/200/300?model=xiaomi-redmi-note-10",
        description:
          "Discover value and performance with the Xiaomi Redmi Note 10. With a 6.43-inch display, a versatile 48MP camera, and 128GB of storage, it's a budget-friendly choice for smartphone users.",
      },
    ],
  },
  laptops: {
    models: [
      {
        id: "l1",
        brand: "Lenovo",
        model: "Ideapad 5",
        price: 899,
        color: ["Silver", "Gray"],
        storage: "512GB",
        size: "15.6 inches",
        img: "https://picsum.photos/200/300?model=lenovo-ideapad-5",
        description:
          "Unleash your productivity with the Lenovo Ideapad 5. This sleek laptop features a 15.6-inch display, a spacious 512GB SSD, and a stylish Silver and Gray color scheme. Whether for work or entertainment, it's a reliable companion.",
      },
      {
        id: "l2",
        brand: "Lenovo",
        model: "ThinkPad X1 Carbon",
        price: 1499,
        color: ["Black"],
        storage: "1TB",
        size: "14 inches",
        img: "https://picsum.photos/200/300?model=lenovo-thinkpad-x1-carbon",
        description:
          "Experience premium computing with the Lenovo ThinkPad X1 Carbon. With a 14-inch display, a massive 1TB storage, and a sleek Black design, it's designed for professionals who demand top-notch performance and style.",
      },
      {
        id: "ap1",
        brand: "Apple",
        model: "MacBook Air",
        price: 1099,
        color: ["Gold", "Silver", "Space Gray"],
        storage: "256GB",
        size: "13 inches",
        img: "https://picsum.photos/200/300?model=macbook-air",
        description:
          "Thin, light, and powerful, the MacBook Air is Apple's iconic laptop. Featuring a 13-inch Retina display, 256GB of storage, and a stunning Gold, Silver, or Space Gray finish, it's the ultimate choice for portable computing.",
      },
      {
        id: "ap2",
        brand: "Apple",
        model: "MacBook Pro",
        price: 1799,
        color: ["Space Gray"],
        storage: "512GB",
        size: "16 inches",
        img: "https://picsum.photos/200/300?model=macbook-pro",
        description:
          "For professionals seeking unparalleled performance, the MacBook Pro is the answer. With a 16-inch Retina display, 512GB storage, and a sleek Space Gray design, it's built to handle your most demanding tasks with ease.",
      },
      {
        id: "d1",
        brand: "Dell",
        model: "XPS 13",
        price: 1299,
        color: ["Rose Gold", "Arctic White"],
        storage: "512GB",
        size: "13.4 inches",
        img: "https://picsum.photos/200/300?model=dell-xps-13",
        description:
          "Immerse yourself in the Dell XPS 13 experience. This laptop boasts a 13.4-inch display, 512GB of storage, and a sleek Rose Gold or Arctic White design. Elevate your computing with Dell's premium craftsmanship.",
      },
      {
        id: "hp1",
        brand: "HP",
        model: "Spectre x360",
        price: 1499,
        color: ["Nightfall Black", "Poseidon Blue"],
        storage: "1TB",
        size: "15.6 inches",
        img: "https://picsum.photos/200/300?model=hp-spectre-x360",
        description:
          "Experience the versatility of the HP Spectre x360. With a 15.6-inch display, 1TB storage, and Nightfall Black or Poseidon Blue color options, it adapts to your lifestyle while delivering top-notch performance.",
      },
      {
        id: "d2",
        brand: "Dell",
        model: "Inspiron 14",
        price: 799,
        color: ["Platinum Silver", "Graphite Gray"],
        storage: "256GB",
        size: "14 inches",
        img: "https://picsum.photos/200/300?model=dell-inspiron-14",
        description:
          "Achieve more with the Dell Inspiron 14. Featuring a 14-inch display, 256GB of storage, and a stylish Platinum Silver or Graphite Gray finish, it's a reliable companion for everyday computing.",
      },
      {
        id: "hp2",
        brand: "HP",
        model: "Envy x360",
        price: 1299,
        color: ["Nightfall Black", "Natural Silver"],
        storage: "512GB",
        size: "15.6 inches",
        img: "https://picsum.photos/200/300?model=hp-envy-x360",
        description:
          "Experience versatility and style with the HP Envy x360. With a 15.6-inch display, 512GB of storage, and color options like Nightfall Black and Natural Silver, it adapts to your creative and professional needs.",
      },
      {
        id: "l3",
        brand: "Lenovo",
        model: "ThinkPad T14s",
        price: 1299,
        color: ["Iron Gray", "Silver"],
        storage: "1TB",
        size: "14 inches",
        img: "https://picsum.photos/200/300?model=lenovo-thinkpad-t14s",
        description:
          "Elevate your business with the Lenovo ThinkPad T14s. Featuring a 14-inch display, 1TB storage, and a sleek Iron Gray or Silver design, it's the perfect blend of performance and professionalism.",
      },
      {
        id: "ap3",
        brand: "Apple",
        model: "MacBook Pro 13",
        price: 1599,
        color: ["Silver", "Space Gray"],
        storage: "512GB",
        size: "13 inches",
        img: "https://picsum.photos/200/300?model=macbook-pro-13",
        description:
          "Power meets portability with the MacBook Pro 13. This laptop features a 13-inch Retina display, 512GB of storage, and is available in the classic Silver and Space Gray finishes. Ideal for creative professionals on the go.",
      },
    ],
  },
};

export { data };
